server:
  port: 8081     #端口号
  servlet:
    context-path: /it
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lslands?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # SpringMVC配置
  mvc:
    static-path-pattern: /static/**
  #Thymeleaf引擎模板配置
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type=: text/html
comment.avatar: /images/avatar.png
# mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名匹配映射
  mapper-locations: classpath:mapper/*.xml  #配置MyBatis的xml映射文件路径
  type-aliases-package: com.lslands.bean    #配置XML映射文件中指定的实体类别名路径
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 日志配置
logging:
  level:
    root: info   #指定日志级别
    com.lslands:  debug
  file: log/blog.log

